require(pkr)
tblNCA(Theoph, "Subject", "Time", "conc", dose=320, concUnit="mg/L")
tblNCA(Theoph, "Subject", "Time", "conc", dose=320, down="Log", concUnit="mg/L")
tblNCA(Indometh, "Subject", "time", "conc", dose=25, adm="Bolus", concUnit="mg/L")
tblNCA(Indometh, "Subject", "time", "conc", dose=25, adm="Bolus", down="Log", concUnit="mg/L")
tblNCA(Indometh, "Subject", "time", "conc", dose=25, adm="Infusion", dur=0.25, concUnit="mg/L")
tblNCA(Indometh, "Subject", "time", "conc", dose=25, adm="Infusion", dur=0.25, down="Log", concUnit="mg/L")
tblNCA(Indometh, "Subject", "time", "conc", dose=25, concUnit="mg/L")
tblNCA(Indometh, "Subject", "time", "conc", dose=25, down="Log", concUnit="mg/L")
